# Generated by Django 3.1.2 on 2020-11-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civ',
            name='army_type',
        ),
        migrations.RemoveField(
            model_name='civ',
            name='civilization_bonus',
        ),
        migrations.RemoveField(
            model_name='civ',
            name='expansion',
        ),
        migrations.RemoveField(
            model_name='civ',
            name='name',
        ),
        migrations.RemoveField(
            model_name='civ',
            name='team_bonus',
        ),
        migrations.RemoveField(
            model_name='civ',
            name='unique_tech',
        ),
        migrations.RemoveField(
            model_name='civ',
            name='unique_unit',
        ),
        migrations.AlterField(
            model_name='civ',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
