# Generated by Django 3.1.2 on 2020-11-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_auto_20201118_1627'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Civ',
            new_name='Builds',
        ),
    ]
