# Generated by Django 3.1.1 on 2020-10-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
